language: java
sudo: false

matrix:
  include:
# Target option 6 is no longer supported. Use 7 or later.
#  - env:
#      - ZULUJDK=12
  - env:
      - ZULUJDK=11
  - env:
      - ZULUJDK=10
  - env:
      - ZULUJDK=9
  - env:
      - ZULUJDK=8
  - env:
      - ZULUJDK=7
# TLS error
#  - env:
#      - ZULUJDK=6

before_install:
  # installing the rpm package 
  - sudo apt-get update -qq
  - sudo apt-get install -qq rpm
  # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
  - "[[ -d $HOME/.sdkman/bin/ ]] || rm -rf $HOME/.sdkman/"
  - curl -sL https://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"

install:
  - sdk install java $(sdk list java | grep -o "$ZULUJDK\.[0-9\.]*-zulu" | head -1)
  - unset JAVA_HOME

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"

script:
  - ./mvnw -version
  - ./mvnw clean package -P full
  - mvn test -Dsurefire.runOrder=alphabetical
  - mvn test -Dsurefire.runOrder=random

